# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OSdnQRvj3GefzpIEIDwOytDghCU4w_Gx
"""

import matplotlib.pyplot as plt
import numpy as np
x=np.array([-1,15])
y=np.array([0,450])
plt.plot(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([0,9,3])
y=np.array([0,450,7])
z=np.array([0,598,25])
plt.plot(x,y,z)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([0,7,2,5,27,39,58,77])
y=np.array([0,873,6,1,15,39,523,71])
plt.plot(x,y,z)
plt.show()